#!/usr/bin/env node

const fs = require('node:fs');

// Export the core function for testing while keeping the script executable
function wc(filename, flag, callback) {
  fs.stat(filename, (err, stats) => {
    if (err) {
      callback(err);
      return;
    }

    if (flag !== '-c' && flag !== '-l' && flag !== '-w') {
      callback(null, '');
      return;
    }

    if (flag === '-c') {
      callback(null, `${stats.size} ${filename}`);
    }

    if (flag === '-l') {
      fs.readFile(filename, 'utf8', (err, data) => {
        if (err) {
          callback(err);
          return;
        }
        const lineCount = data ? data.split('\n').length : 0;
        callback(null, `${lineCount} ${filename}`);
      });
    }

    if (flag === '-w') {
      fs.readFile(filename, 'utf8', (err, data) => {
        if (err) {
          callback(err);
          return;
        }
        const wordCount = data ? data.trim().split(/\s+/).length : 0;
        callback(null, `${wordCount} ${filename}`);
      });
    }

  });
}

// Only run this part when file is executed directly, not when imported
if (require.main === module) {
  const flag = process.argv[2];
  const filename = process.argv[3];

  wc(filename, flag, (err, result) => {
    if (err) {
      console.error(err);
      return;
    }
    if (result) {
      console.log(result);
    }
  });
}

// This export will only be used by the test file
module.exports = wc;
